[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
cometd-client = { path = "../../", features = ["all"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
